[pyprland]
plugins = ["scratchpads", "expose"]

# [scratchpads.volume]
# animation = "fromRight"
# command = "pavucontrol"
# class = "pavucontrol"
# size = "40% 90%"
# unfocus = "hide"
# lazy = true

[scratchpads.term]
animation = "fromBottom"
command = "kitty --class scratchpad"
class = "scratchpad"
# size = "1400px 60%"
# max_size = "1920px 100%"
# margin = 180

[scratchpads.ranger]
command = "kitty --class scratchpad -e ranger"
margin = 50
animation = "fromTop"

# [scratchpads.files]
# animation = "fromTop"
# command = "pcmanfm --class scratchpad"
# class = "scratchpad"
# margin = 50

[scratchpads.updatez]
animation = "fromBottom"
command = "kitty --class scratchpad -e update-menu"
class = "scratchpad"
# size = "1400px 60%"
# max_size = "1920px 100%"
# margin = 180
